
# PBL Review 2

![Hardware Photo](asset/pexels-pixabay-159235.jpg)

## Team:
> - Mahir Patel
> - Divyesh Patel
> - Diya Patel
> - Meet Motta
> - Tushar Patel

## Abstract:
> This is the Data of Hardware which is now a day a major concern for many people working, so to know the best hardware this is the **exploratory analysis** through which we are carrying out the insider's report on the hardware available out there.

In [2]:
import pandas as pd

### Data Imported
> **Note**: This Data is taken from https://www.kaggle.com/datasets/michaelbryantds/cpu-and-gpu-product-data for the purpose of analyis

### About Dataset

A dataset with 2,185 CPUs and 2,668 GPUs to help researchers understand the development trend of CPUs and GPUs.

Here are some interesting facts supported by the data:
- Moore's Law still holds, especially in GPUs.
- Dannard Scaling is still valid in general.
- CPUs have higher frequencies, but GPUs are catching up.
- GPU performance doubles every 1.5 years.
- GPU performance improvement is a joint effect of smaller transistors, larger die size, and higher frequency.
- High-end GPUs tends to first use new semiconductor technologies. Low-end GPUs may use old technologies for a few years.

In [3]:
data = "chip_dataset.csv"
data_df = pd.read_csv(data)

In [14]:
data_df = data_df.drop(columns=["Unnamed: 0"])

In [15]:
data_df.value_counts()

Product                         Type  Release Date  Process Size (nm)  TDP (W)  Die Size (mm^2)  Transistors (million)  Freq (MHz)  Foundry  Vendor  FP16 GFLOPS  FP32 GFLOPS  FP64 GFLOPS
NVIDIA GeForce GTX 1050 Mobile  GPU   2017-01-03    14.0               75.0     132.0            3300.0                 1354.0      Samsung  NVIDIA  29.86        1911.0       59.72          2
AMD Radeon RX 560X Mobile       GPU   2018-04-11    14.0               65.0     123.0            3000.0                 1275.0      GF       AMD     2611.00      2611.0       163.20         2
AMD Atari VCS 400 GPU           GPU   2020-12-14    14.0               15.0     210.0            4940.0                 300.0       GF       AMD     922.40       461.2        28.82          1
NVIDIA GeForce GTX 1650 TU116   GPU   2020-07-07    12.0               80.0     284.0            6600.0                 1410.0      TSMC     NVIDIA  5699.00      2849.0       89.04          1
NVIDIA GeForce MX150 GP107      GPU   2019-02-23    14.0               25.0     132.0            3300.0                 1469.0      Samsung  NVIDIA  18.38        1177.0       36.77          1
                                                                                                                                                                                             ..
AMD Radeon RX 560 Mobile        GPU   2017-01-05    14.0               55.0     123.0            3000.0                 1000.0      GF       AMD     1887.00      1887.0       117.90         1
                                                                                                                        784.0       GF       AMD     1849.00      1849.0       115.60         1
AMD Radeon RX 560 896SP         GPU   2017-07-04    14.0               45.0     123.0            3000.0                 1090.0      GF       AMD     2106.00      2106.0       131.60         1
AMD Radeon RX 560               GPU   2017-04-18    14.0               75.0     123.0            3000.0                 1175.0      GF       AMD     2611.00      2611.0       163.20         1
NVIDIA Tesla V100S PCIe 32 GB   GPU   2019-11-26    12.0               250.0    815.0            21100.0                1245.0      TSMC     NVIDIA  32710.00     16350.0      8177.00        1
Length: 426, dtype: int64

In [17]:
import numpy as np

# average process size

average_process_size = np.mean(data_df["Process Size (nm)"])
print("The Average process size is:", average_process_size)

# average TDP (Thermal Design Power)

average_tdp = np.mean(data_df["TDP (W)"])
print("The average Thermal Design Power is:", average_tdp)

The Average process size is: 55.10959752321981
The average Thermal Design Power is: 81.35998107852413

In [18]:
# Let's Take a summary of all the numerical data
data_summary = data_df[["Process Size (nm)", "TDP (W)", "Die Size (mm^2)", "Transistors (million)", "Freq (MHz)", "FP16 GFLOPS", "FP32 GFLOPS", "FP64 GFLOPS"]]
data_summary

,Process Size (nm),TDP (W),Die Size (mm^2),Transistors (million),Freq (MHz),FP16 GFLOPS,FP32 GFLOPS,FP64 GFLOPS
0,65.0,45.0,77.0,122.0,2200.0,NaN,NaN,NaN
1,14.0,35.0,192.0,4800.0,3200.0,NaN,NaN,NaN
2,10.0,28.0,NaN,NaN,2600.0,NaN,NaN,NaN
3,22.0,80.0,160.0,1400.0,1800.0,NaN,NaN,NaN
4,45.0,125.0,258.0,758.0,3700.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
4849,40.0,75.0,332.0,1950.0,450.0,NaN,432.0,36.0
4850,90.0,7.0,NaN,NaN,250.0,NaN,NaN,NaN
4851,40.0,23.0,100.0,486.0,500.0,NaN,52.8,NaN
4852,150.0,NaN,65.0,29.0,250.0,NaN,NaN,NaN
4853,65.0,NaN,86.0,210.0,540.0,NaN,20.8,NaN

In [20]:
data_summary.describe()

,Process Size (nm),TDP (W),Die Size (mm^2),Transistors (million),Freq (MHz),FP16 GFLOPS,FP32 GFLOPS,FP64 GFLOPS
count,4845.000000,4228.000000,4139.000000,4143.000000,4854.000000,536.000000,1948.000000,1306.000000
mean,55.109598,81.359981,188.440445,1929.922279,1484.406057,8397.459851,2134.756653,363.670511
std,44.998676,76.807808,126.189383,4044.891098,1066.701523,13799.551131,3898.431487,1145.931856
min,0.000000,1.000000,1.000000,8.000000,100.000000,10.020000,12.800000,3.600000
25%,22.000000,33.000000,104.000000,154.000000,590.000000,768.800000,257.300000,38.295000
50%,40.000000,65.000000,148.000000,624.000000,1073.500000,2965.500000,696.000000,89.280000
75%,90.000000,100.000000,239.000000,1550.000000,2400.000000,10600.000000,2116.750000,220.000000
max,250.000000,900.000000,826.000000,54200.000000,4700.000000,184600.000000,40000.000000,11540.000000

In [7]:
data_df_vendors = data_df["Vendor"]
data_df_vendors.unique()

array(['AMD', 'Intel', 'Other', 'NVIDIA', 'ATI'], dtype=object)

# AMD Hardware

![AMD hardware](asset/th.jpeg)

In [21]:
data_df_amd = data_df[(data_df["Vendor"] == 'AMD')]
data_df_amd

,Product,Type,Release Date,Process Size (nm),TDP (W),Die Size (mm^2),Transistors (million),Freq (MHz),Foundry,Vendor,FP16 GFLOPS,FP32 GFLOPS,FP64 GFLOPS
0,AMD Athlon 64 3500+,CPU,2007-02-20,65.0,45.0,77.0,122.0,2200.0,Unknown,AMD,NaN,NaN,NaN
1,AMD Athlon 200GE,CPU,2018-09-06,14.0,35.0,192.0,4800.0,3200.0,Unknown,AMD,NaN,NaN,NaN
4,AMD Phenom II X4 980 BE,CPU,2011-05-03,45.0,125.0,258.0,758.0,3700.0,Unknown,AMD,NaN,NaN,NaN
6,AMD Phenom X4 9750 (125W),CPU,2008-03-27,65.0,125.0,285.0,450.0,2400.0,Unknown,AMD,NaN,NaN,NaN
9,AMD Athlon 64 X2 4200+,CPU,2006-05-23,90.0,89.0,156.0,154.0,2200.0,Unknown,AMD,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4829,AMD Radeon R5 220 OEM,GPU,2013-12-21,40.0,19.0,59.0,292.0,650.0,TSMC,AMD,NaN,104.0,NaN
4830,AMD Radeon RX 550X Mobile,GPU,2018-04-11,14.0,50.0,103.0,2200.0,1100.0,GF,AMD,1505.0,1505.0,94.08
4833,AMD Radeon R9 280X2,GPU,NaT,28.0,375.0,352.0,4313.0,950.0,TSMC,AMD,NaN,4096.0,1024.00
4836,AMD Radeon Instinct MI25,GPU,2017-06-27,14.0,300.0,495.0,12500.0,1400.0,GF,AMD,24580.0,12290.0,768.00
4839,AMD Radeon R7 350 640SP,GPU,2019-01-07,28.0,55.0,123.0,1500.0,925.0,TSMC,AMD,NaN,1184.0,74.00

In [22]:
data_df_amd.Type.value_counts()

CPU    950
GPU    712
Name: Type, dtype: int64

In [36]:
data_df_amd_summary = data_df_amd[["Process Size (nm)", "TDP (W)", "Die Size (mm^2)", "Transistors (million)", "Freq (MHz)", "FP16 GFLOPS", "FP32 GFLOPS", "FP64 GFLOPS"]].describe()

In [38]:
data_df_amd_summary

,Process Size (nm),TDP (W),Die Size (mm^2),Transistors (million),Freq (MHz),FP16 GFLOPS,FP32 GFLOPS,FP64 GFLOPS
count,1662.000000,1542.000000,1484.000000,1553.000000,1662.000000,259.000000,711.000000,502.000000
mean,48.087244,84.830739,185.882075,2178.277527,1744.011432,7426.726641,2261.669001,314.167614
std,39.756092,70.622103,99.060184,3311.147900,985.915499,13837.617245,3138.238179,804.474584
min,7.000000,4.000000,1.000000,37.000000,200.000000,153.600000,25.600000,3.600000
25%,28.000000,37.250000,110.000000,233.000000,893.250000,1309.500000,537.600000,49.150000
50%,32.000000,65.000000,183.000000,1178.000000,1700.000000,3297.000000,1008.000000,110.100000
75%,65.000000,95.000000,246.000000,2800.000000,2400.000000,8165.000000,2574.000000,330.575000
max,180.000000,580.000000,750.000000,50000.000000,4700.000000,184600.000000,23070.000000,11540.000000